### ISSUE TITLE
Can't find zimbra_pflogsumm.pl

### ISSUE THREAD

**Issue by VMax2** [jorgedlcruz/zimbra-grafana#8]
Hi, at this address the file is no more available

https://raw.githubusercontent.com/jorgedlcruz/zimbra-grafana/master/zimbra_pflogsumm.pl

Can you help me please?

Thank you in advance

**Comment by jorgedlcruz** [comment]
Hello,
Yes, I am not using that anymore, the latest information and Dashboard leverages the official OpenLDAP and official postfix output, more info here https://grafana.com/grafana/dashboards/2846

**Comment by VMax2** [comment]
Thank you, i have just finished installing everithing by the old way... well, later i will try the new one :-) 

Have a good time

**Comment by VMax2** [comment]
Everything went very well, now the dashboard is up and running , thank you

**Comment by Daly123456** [comment]
i’am using influx and telegraf to monitor my zimbra server in order to display outgoing mails i tried this tuto ‘‘https://computingforgeeks.com/how-to-monitor-zimbra-server-with-grafana-influxdb-and-telegraf/’’
and as i saw on tutorials there are all using ‘‘zimbra_pflogsumm.pl’’
but this file .pl is empty and when using ''curl -sL https://raw.githubusercontent.com/jorgedlcruz/zimbra-grafana/master/zimbra_pflogsumm.pl | sudo tee /opt/zimbra/common/bin/zimbra_pflogsumm.pl
‘’
the file is not found !

i just wanted to display outgoing mails  and zimbra queues ! 
how can i do that please ?

**Comment by jorgedlcruz** [comment]
Hello,
I've removed the .pl a long time ago in favor of using native telegraf inputs from postfix and OpenLDAP, try the new config and let me know, it should work just as fine.

**Comment by Daly123456** [comment]
it's working and it's the second time i'am using your dashboard all works good but i just need 
- to display outgoing mails 
and i got problem with zimbra queues it show no data (how can i solve that )
?

**Comment by jorgedlcruz** [comment]
Outgoing mails the postfix input doesn't take them, so please open another issue so I will need to investigate.

For the queues, should show some data, open another issue so we track that differently, this one is closed.
